#build.properties header
#Mon Mar 24 11:37:08 KST 2003

jar.name=XCron-1.1
lib.dir=${xcron.home}/lib
src.dir=${xcron.home}/src
build.dir=${xcron.home}/build
common.dir=${xcron.home}/common
class.dir=${xcron.home}/classes
api.dir=${xcron.home}/docs/api
temp.dir=${xcron.home}/temp
work.dir=${xcron.home}/work
buildxml.dir=${xcron.home}/buildxml