#build.properties header
#Mon Mar 24 11:37:08 KST 2003


lib.dir=${jedi.home}/webapps/WEB-INF/lib
src.dir=${jedi.home}/src
#webapps.dir=${jedi.home}/webapps
webapps.dir=${jedi.home}/servers/tomcat_6.0.29/webapps/jedi/wfms
build.dir=${jedi.home}/buildxml
#common.dir=${jedi.home}/common
common.dir=${jedi.home}/webapps/WEB-INF/classes
#api.dir=${jedi.home}/docs/api
#temp.dir=${jedi.home}/temp
work.dir=${jedi.home}/webapps
buildxml.dir=${jedi.home}/buildxml