/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-11-13 05:35:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import com.locus.jedi.waf.*;
import com.locus.jedi.waf.controller.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


   Throwable t = exception;
   String message = t.getMessage();
   if(exception instanceof ServletException){
	   ServletException e = (ServletException)exception;
	   if(e.getRootCause() == null) t = e;
	   else t = e.getRootCause();
   }
   RequestSpec spec = (RequestSpec)request.getAttribute(WebKeys.CURRENT_REQUEST_KEY); 
   String temp="";
   if(spec != null) temp = spec.getDescription();
   

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>무제 문서</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("function MM_reloadPage(init) {  //reloads the window if Nav4 resized\r\n");
      out.write("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {\r\n");
      out.write("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}\r\n");
      out.write("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();\r\n");
      out.write("}\r\n");
      out.write("MM_reloadPage(true);\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("td {\r\n");
      out.write("\tfont-family: \"굴림\", \"굴림체\", \"돋움\", \"돋움체\";\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd {\r\n");
      out.write("\tborder: 1px solid #dddddd;\r\n");
      out.write("\tbackground-color: #EFF3F6;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body leftmargin=\"5\" topmargin=\"5\">\r\n");
      out.write("\t<table width=\"400\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\tcellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getContextPath() );
      out.write("/common/images/error-4.gif\"\r\n");
      out.write("\t\t\t\twidth=\"400\" height=\"108\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td\r\n");
      out.write("\t\t\t\tbackground=\"");
      out.print(request.getContextPath() );
      out.write("/common/images/error-2.gif\">\r\n");
      out.write("\t\t\t\t<table width=\"370\" border=\"0\" align=\"center\" cellpadding=\"3\"\r\n");
      out.write("\t\t\t\t\tcellspacing=\"1\" class=\"bd\" style=\"table-layout: fixed\">\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t\t<td width=\"120\" align=\"center\" bgcolor=\"#f9f9f9\"><font\r\n");
      out.write("\t\t\t\t\t\t\tcolor=\"#006699\">Request URL</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( request.getAttribute(WebKeys.CURRENT_REQUEST_NAME));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#f9f9f9\"><font color=\"#006699\">Request\r\n");
      out.write("\t\t\t\t\t\t\t\tDescription</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( temp);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#f9f9f9\"><font color=\"#006699\">Exception\r\n");
      out.write("\t\t\t\t\t\t\t\tType</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(t.getClass().getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\" bgcolor=\"#f9f9f9\"><font color=\"#006699\">Exception\r\n");
      out.write("\t\t\t\t\t\t\t\tMessage</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(message);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#f9f9f9\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" align=\"center\"><font color=\"#006699\">Exception\r\n");
      out.write("\t\t\t\t\t\t\t\ttrace</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" align=\"center\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 360; height =150; overflow: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
t.printStackTrace(new PrintWriter(out));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table> <br>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getContextPath() );
      out.write("/common/images/error-3.gif\"\r\n");
      out.write("\t\t\t\twidth=\"400\" height=\"8\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
