/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-11-17 01:33:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jedix.xwing.util.*;
import org.json.*;
import com.locus.jedi.log.*;
import com.locus.jedi.transfer.*;
import com.locus.jedi.waf.*;

public final class Xwing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      com.locus.jedi.waf.controller.JediRequest jediReq = null;
      jediReq = (com.locus.jedi.waf.controller.JediRequest) _jspx_page_context.getAttribute("jediReq", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (jediReq == null){
        jediReq = new com.locus.jedi.waf.controller.JediRequest();
        _jspx_page_context.setAttribute("jediReq", jediReq, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      com.locus.jedi.waf.controller.JediResponse jediRes = null;
      jediRes = (com.locus.jedi.waf.controller.JediResponse) _jspx_page_context.getAttribute("jediRes", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (jediRes == null){
        jediRes = new com.locus.jedi.waf.controller.JediResponse();
        _jspx_page_context.setAttribute("jediRes", jediRes, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

CommonDTO common = jediReq.getCommonDTO();
if(common != null && common.getUserId() !=null && !common.getUserId().equals("???")){
			jediRes.param.addValue("user_id", common.getUserId());
			jediRes.param.addValue("clientIp", common.getClientIp());
			jediRes.param.addValue("user_name", common.getUserName());
   			jediRes.param.addValue("team_cd", common.getAttribute("team_cd"));
 			jediRes.param.addValue("err_cnt", common.getAttribute("err_cnt"));
 			jediRes.param.addValue("grade_cd", common.getAttribute("grade_cd"));
 			jediRes.param.addValue("grade_name", common.getAttribute("grade_name"));
 			jediRes.param.addValue("client_ip", common.getAttribute("client_ip"));
 			jediRes.param.addValue("server_ip", common.getAttribute("server_ip"));
			jediRes.param.addValue("extention", common.getAttribute("extention"));
			jediRes.param.addValue("cti_id", common.getAttribute("cti_id"));
			jediRes.param.addValue("login_date", common.getAttribute("login_date"));
			jediRes.param.addValue("login_time", common.getAttribute("login_time"));

			jediRes.param.addValue("server_id", common.getAttribute("server_id"));
 			jediRes.param.addValue("server_ip", common.getAttribute("server_ip"));
 			jediRes.param.addValue("server_port", common.getAttribute("server_port"));
 			jediRes.param.addValue("contextRoot", common.getAttribute("contextRoot"));
 			jediRes.param.addValue("serverUrl", common.getAttribute("serverUrl"));
}
JSONObject jsonStr =XwingProcessor.sendResponse(jediRes, jediRes.param); 
ErrorLogger.debug("Xwing.jsp out : "+ jsonStr.toString());

      out.print(jsonStr.toString());
      out.write('\r');
      out.write('\n');
out.flush();
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
