org.jcrontab.version=2.0.RC1
org.xml.sax.driver=org.apache.xerces.parsers.SAXParser
org.jcrontab.data.datasource=org.jcrontab.data.XMLSource
org.jcrontab.log.Logger=com.inticube.xcron.logs.ScheduleLogger
org.jcrontab.Crontab.refreshFrequency=3