#XCron Home Directory
xcron.home = D:/workspace/MSENS_OB_FINAL/XCron

#XCron DataSource Configuration File Path
path.xcron.datasource.config = /config/datasource/datasourceconfig_msens.xml

#XCron Service Configure File Path
path.xcron.service.config = /config/service/serviceconfig_msens.xml


#XCron Schedule Configure File Path
path.xcron.schedule.config = /config/schedule/crontab_msens.xml


#XCron Administrator's Configure File Path
path.xcron.admin.config = /config/admin/adminconfig_empty.xml

#XCron Cluster Configure File Path
path.cluster.config = /config/cluster/cluster_msens.xml

#XCron Notice Service after XCron Shutdown
xcron.admin.restart.notice.service = empty_notice_service

#XCron Server Port
xcron.server.port = 5292

#XCron Shutdown Listener Port
xcron.shutdown.listener.port = 2006

#XCron Cluster Load Balance Turn On
xcron.cluster.loadbalance = false

#XCron Cluster Topology Checker Interval Time (m/s)
xcron.cluster.topologychecker.intervaltime = 10000

#XCron Cluster Network Protocol
path.cluster.protocol.config = /config/cluster/protocol/tcp.xml

#XCron Service Script BeanShell Path
path.xcron.service.script = /config/service/servicehelper.bsh

#XCron Log Config Path
path.xcron.log.config = /config/logConfig.xml

#XCron OS Monitoring Service Turn On
xcron.os.monitoring = false

#XCron Performance Monitoring Interval Time (m/s)
xcron.os.monitoring.intervaltime = 10000

#XCron Health Monitoring Time Interval (Default : 60000 m/s) 
xcron.health.monitoring.intervaltime = 60000

#XCron Service's RequestService Time Out (Default : 3600000 m/s) 
xcron.health.requestservice.timeout = 3600000

#XCron Scheduler's Time Out (Default : 180000 m/s)
xcron.health.scheduler.timeout = 180000
