/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2020-01-08 08:46:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import com.locus.jedi.service.sql.*;
import com.locus.jedi.biz.*;
import com.locus.jedi.waf.controller.*;
import com.locus.jedi.transfer.*;
import jedix.xwing.util.*;
import org.json.*;
import java.util.regex.*;
import sens.service.webaction.Timestamp;

public final class session_005ftimeout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.locus.jedi.waf.controller.JediRequest jediReq = null;
      jediReq = (com.locus.jedi.waf.controller.JediRequest) _jspx_page_context.getAttribute("jediReq", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (jediReq == null){
        jediReq = new com.locus.jedi.waf.controller.JediRequest();
        _jspx_page_context.setAttribute("jediReq", jediReq, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.locus.jedi.waf.controller.JediResponse jediRes = null;
      jediRes = (com.locus.jedi.waf.controller.JediResponse) _jspx_page_context.getAttribute("jediRes", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (jediRes == null){
        jediRes = new com.locus.jedi.waf.controller.JediResponse();
        _jspx_page_context.setAttribute("jediRes", jediRes, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	Timestamp timestamp = null;
	HttpServletRequest req = jediReq.getHttpServletRequest();

	timestamp = new Timestamp();
	String connect_ip = req.getRemoteAddr();
	
	try{
		timestamp.STimeoutInsertTimeStamp(connect_ip);
		timestamp.STimeoutInsertWorkStat(connect_ip);
	}catch(Exception e){
		e.printStackTrace();
	}


	jediRes.setResultCode("SessionTimeOut");
	jediRes.setResultMessage("다른 PC에서 동시접속으로 인해 세션이 만료되었습니다. 다시 로그인 해주세요.");
	jediRes.setError(true);
	
	/* for character injection -> XSS 유효성 체크 추가(2018.07.27)*/

	String pattern = "<(/)?([a-zA-Z]*)(\\s[a-zA-Z]*=[^>]*)?(\\s)*(/)?>";
	Pattern p = Pattern.compile(pattern);
	String [] keysRes = jediRes.param.keys();
	String newKey = "";
	String newVal = "";
	
	for(int i =0; i< keysRes.length; i++){
		Matcher m = p.matcher(keysRes[i]);
		
		if(m.find()){ //key에서 걸릴 때
			newKey = keysRes[i].replaceAll(pattern, "").replaceAll("script", "");
			newVal = jediRes.param.getValue(keysRes[i]).toString();
			
			jediRes.param.remove(keysRes[i]);
			jediRes.param.addValue(newKey, newVal);
			
		}
		
		String val = jediRes.param.getValue(keysRes[i],"").toString();
		Matcher m_val = p.matcher(val);
		
		if(m_val.find() && val.indexOf("_QUERY") == -1){ //VAL에서 걸릴 때
			newKey = keysRes[i];
			newVal = (jediRes.param.getValue(keysRes[i]).toString()).replaceAll(pattern, "").replaceAll("script", "");
			
			jediRes.param.addValue(newKey, newVal);
					
		}
		
		if(jediRes.getResultMessage() != null) jediRes.setResultMessage(jediRes.getResultMessage().replaceAll(pattern, "").replaceAll("script", ""));
	}	
	
	JSONObject jsonStr = XwingProcessor.sendResponse(jediRes,jediRes.param);

      out.write('\r');
      out.write('\n');
      out.print(jsonStr.toString());
      out.write('\r');
      out.write('\n');
out.flush();
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
