
#================================================
# Expired Info
#================================================
installed_date = 20151001
duration_day = 1000
was_path = D:\\workspace\\Eclipse\\MSENS\\servers\\tomcat_7.0.42
dir_path = D:\\workspace\\Eclipse\\MSENS\\webapps
