#jedi home directory
jedi.home		= /D:/MSENS_AIG_NEW/AIG_QSENS_FINAL/webapps

#requests.xml file path
path.requests.xml	= /config/requests

#biz_requests.xml file path
path.biz_requests.xml = /config/biz_requests.xml

#webpages.xml configuration path
path.webpages.xml	= /config/webpages.xml

#environment.xml configuration
path.environment.xml	= /config/environment.xml

#exceptions.xml configuration
path.excetpions.xml	= /config/exceptions.xml

#BizDelegationImpl class name
class.BizDelegationImpl= com.locus.jedi.waf.delegation.BizDelegationImpl

#Loggers Configuration
path.logConfig.xml	= /config/logConfig.xml

#servers Configuration(RmiAgent)
path.servers.xml	= /config/servers.xml

#Socket Configuration
path.socketconfig.xml = /config/socketconfig.xml

#Query Collection
path.query_collection.xml= /resource/querys

#Host_services
path.host_service.xml = /resource/host_services.xml
