/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-12-04 04:57:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"> \r\n");
      out.write("<link rel=\"shortcut icon\" href=\"msens_icon.ico\" />\r\n");
      out.write("<link rel=\"icon\" href=\"msens_icon.ico\" />\r\n");
      out.write("<script>\r\n");
      out.write("function setCookie(cName, cValue, cDay){\r\n");
      out.write("    var expire = new Date();\r\n");
      out.write("    expire.setDate(expire.getDate() + cDay);\r\n");
      out.write("    cookies = cName + '=' + escape(cValue) + '; path=/ '; \r\n");
      out.write("    if(typeof cDay != 'undefined') cookies += ';expires=' + expire.toGMTString() + ';';\r\n");
      out.write("    document.cookie = cookies;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getCookie(cName) {\r\n");
      out.write("    cName = cName + '=';\r\n");
      out.write("    var cookieData = document.cookie;\r\n");
      out.write("    var start = cookieData.indexOf(cName);\r\n");
      out.write("    var cValue = '';\r\n");
      out.write("    if(start != -1){\r\n");
      out.write("         start += cName.length;\r\n");
      out.write("         var end = cookieData.indexOf(';', start);\r\n");
      out.write("         if(end == -1)end = cookieData.length;\r\n");
      out.write("         cValue = cookieData.substring(start, end);\r\n");
      out.write("    }\r\n");
      out.write("    return unescape(cValue);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function onload() {\r\n");
      out.write("\tvar agt = navigator.userAgent.toLowerCase();\r\n");
      out.write("\t\r\n");
      out.write("\t//if (agt.indexOf(\"chrome\") != -1){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar w = window.open(\"./common/login.xhtml\", \"LOGIN\",\"width=679, height=447, left=0, top=0, location=no, resizable=0\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (w == null) {\r\n");
      out.write("\t\t\talert(\"팝업차단을 해제 후 접속 해 주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.notice.src=\"./images/go_vsens.jpg\";\r\n");
      out.write("\t\tsetTimeout(\"window.close()\", 300);\r\n");
      out.write("\t\t//window.open(\"about:_blank\", \"_self\").self.close();\r\n");
      out.write("\t//} else {\r\n");
      out.write("\t//\tdocument.notice.src=\"./images/brower_notice.jpg\";\r\n");
      out.write("\t//\tsleep(500);\r\n");
      out.write("\t//\tdocument.location= location.href + \"/temp/ChromeStandaloneSetup.exe\";\r\n");
      out.write("\t//}\r\n");
      out.write("\t/*\r\n");
      out.write("\t// 인터넷옵션 신뢰할 수 있는 사이트에 서버 IP 추가\r\n");
      out.write("\tif(window.navigator.userAgent.indexOf(\"MSIE\")>=0){\r\n");
      out.write("\t\t//fncIconCreate();\r\n");
      out.write("\t} \r\n");
      out.write("\tvar w = window.open(\"./common/login.xhtml\", \"LOGIN\",\"width=796, height=596, left=0, top=0, location=no, resizable=no\");\r\n");
      out.write("\t\r\n");
      out.write("\tif (w == null) {\r\n");
      out.write("\t\talert(\"팝업차단을 해제 후 접속 해 주세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t//window.open(\"about:_blank\", \"_self\").close(); //실제 사용시 주석 제거\t\t\r\n");
      out.write("\t*/\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t* Chrome 체크 후 설치\r\n");
      out.write("\t*/\r\n");
      out.write("\t//var agt = navigator.userAgent.toLowerCase();\r\n");
      out.write("\t//if (agt.indexOf(\"chrome\") != -1){\r\n");
      out.write("\t//\tvar v_flag = getCookie(\"make_icon\");\r\n");
      out.write("\t//\tif(v_flag == \"make\"){\r\n");
      out.write("\t\t\t/*  var w = window.open(\"./common/login.xhtml\", \"LOGIN\",\"width=796, height=596, left=0, top=0, location=no, resizable=no\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (w == null) {\r\n");
      out.write("\t\t\t\talert(\"팝업차단을 해제 후 접속 해 주세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\t\t\t//window.open(\"about:_blank\", \"_self\").close();\r\n");
      out.write("\t//\t} else {\r\n");
      out.write("\t//\t\tsetCookie(\"make_icon\", \"make\", 365);\r\n");
      out.write("\t//\t\tdocument.notice.src=\"./images/makeinfo.jpg\";\r\n");
      out.write("\t//\t}\r\n");
      out.write("\t//} else {\r\n");
      out.write("\t//\tdocument.notice.src=\"./images/brower_notice.jpg\";\r\n");
      out.write("\t//\tsleep(500);\r\n");
      out.write("\t//\tdocument.location= location.href + \"/temp/ChromeStandaloneSetup.exe\";\r\n");
      out.write("\t//}\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fncIconCreate() {\t\r\n");
      out.write("\tvar WshShell = new ActiveXObject(\"WScript.Shell\");\r\n");
      out.write("\tstrDesktop = WshShell.SpecialFolders(\"Desktop\");\r\n");
      out.write("\t\r\n");
      out.write("     var oUrlLink = WshShell.CreateShortcut(strDesktop + \"\\\\IS_VOC.url\");\r\n");
      out.write("\t //if(oUrlLink.TargetPath.indexOf(\"http://10.1.12.6:8080/IS_CNVu\") > -1)\treturn;\r\n");
      out.write("\t \r\n");
      out.write("\t oUrlLink.TargetPath = \"http://10.1.15.169:8090/MSENS/index.jsp\";\r\n");
      out.write("     oUrlLink.Save();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sleep(milliseconds) {\r\n");
      out.write("\tvar start = new Date().getTime();\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i = 0; i < 1e7; i++) {\r\n");
      out.write("\t\tif((new Date().getTime() - start) > milliseconds){\r\n");
      out.write("\t    \tbreak;\r\n");
      out.write("\t   \t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<title>M-SENS</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"onload()\">\r\n");
      out.write("<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t<img name=\"notice\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
