waveform_period=1000
waveform_peak=3
#-1 means unlimited, measure is 1000 -> 1Kbyte
waveform_MinFileSize=1000 
waveform_MaxFileSize=-1
waveform_MaxPeriod=-1

aes_key=AigVA_1544ARS_WebService000001
cipher_key=aigva-msens-cipher@20180517-qwer1
