sftp_host=10.48.241.13
sftp_host_dev=10.48.247.182
sftp_port=22
sftp_user=swFcrNfcntLI8xFRR3+dIg==
sftp_password=cQwgfukERYQSmWS4hPkFhA==
remote_path=/sw/msens/MSENS_OB/webapps/temp/
local_path=/sw/msens/MSENS_OB/webapps/temp/
local_input_path=/sw/msens/MSENS_OB/webapps/temp/input/
local_output_path=/sw/msens/MSENS_OB/webapps/temp/
sox_dir=/usr/bin/sox
sftp_path=SponsorRec/UPLOAD/
serverMode=prod
