/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-05-04 08:18:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.MultipartRequest;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import java.util.Enumeration;
import java.io.File;
import java.net.*;

public final class fileUpload2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	try {

		final int MAX_SIZE 			= 1024*1024*100; // 최대 파일 사이즈.
		//final String FILE_DIRECTORY = "/home/hansol/dev/engine/LA/source/lang/lang_test/docs"; ///upload_file"; // 파일 저장 경로.
		final String FILE_DIRECTORY = "/uploadFiles"; // 파일 저장 경로.
	
		System.out.println("####fileUpload2.jsp####");
		// 업로드 경로(realPath는 서버의 절대경로를 읽어옴)
		//String archive 			= FILE_DIRECTORY; //request.getRealPath(FILE_DIRECTORY); 
		String archive 			= request.getRealPath(FILE_DIRECTORY);
		String result 			= null; // 결과값.
		
		// 객체 생성과 동시에 파일업로드가됨. DefaultFileRenamePolicy객체에 의해 파일이름 중복시 자동변경.
		MultipartRequest mr 	= new MultipartRequest(request, archive, MAX_SIZE, "UTF-8", new DefaultFileRenamePolicy());;
		
		System.out.println("####success####");
		
		// 변경되었을수도 있는 파일 이름을 저장하기위해 mr인스턴스에서 업로드된 파일 이름+경로를 가져옴.
		String fileName = URLEncoder.encode( mr.getFilesystemName("files") );
		result = archive + "\\" + mr.getFilesystemName("files");
		result= result.replace("\\", "/");
		System.out.println("####Uploaded Path####"+result);
		
		// 정상적으로 업로드 되었을경우 파일경로와 에러코드 0번을 JSON형태로 뿌림.
		System.out.println("{\"ResultCode\":\"0\",\"ResultMessage\":\"no message\", \"FilePath\":\""+ result +"\", \"Error\":\"0\"}");
		out.println("{\"ResultCode\":\"0\",\"ResultMessage\":\"no message\", \"FilePath\":\""+ result +"\", \"Error\":\"0\"}");
		
		//System.out.println("{\"ResultCode\":\"0\",\"ResultMessage\":\"no message\", \"FilePath\":\""+ result +"\"}");
		//out.println("{\"ResultCode\":\"0\",\"ResultMessage\":\"no message\", \"FilePath\":\""+ result +"\"}");
		
	} catch (Exception e) {
		// 업로드중 에러 발생시 에러코드 1번과  에러메세지를 JSON형태로  뿌림.
		out.println("{\"ResultCode\":\"1\",\"ResultMessage\":\"파일 업로드중 에러 발생!\", \"Error\":\"0\"}");
		e.printStackTrace();
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
